services:
  k8s-app:
    image: henry768/redux-todo-astro:latest
    ports:
      - "4321:4321"
      - "24678:24678"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4321
      - ASTRO_TELEMETRY_DISABLED=1
      - IS_KUBERNETES=true
      - THEME_DEFAULT=dark
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.astro
    command: npm run dev -- --host 0.0.0.0 --watch.usePolling
    restart: unless-stopped
