version: '3.8'

services:
  app:
    image: henry768/redux_todo_in_astro:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    restart: unless-stopped
    
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4321
    command: npm run dev
    restart: unless-stopped
  
  notion-mcp:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NOTION_PORT=3002
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
    command: node server/notion-mcp-server.js
    restart: unless-stopped

  terminal:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    command: bash -c "cd server && npm rebuild node-pty --update-binary && node terminal-server.js"
    privileged: true
    restart: unless-stopped
    
  gasing-mcp:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - "3004:3004"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - GASING_PORT=3004
    command: node src/gasing/division/GasingMCP.js
    restart: unless-stopped
