services:
  app:
    build:
      context: .
      args:
        BUILD_MODE: nocheck
    pull_policy: always
    image: redux-todo-astro:latest
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4321
    command: npm run dev
