services:
  app:
    image: henry768/redux_todo_in_astro:last
    container_name: redux-todo-astro
    ports:
      - "4321:4321"
    env_file:
      - .env
    command: npm run dev


  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"
    entrypoint: ["/bin/sh", "-c"]
    command: ["ollama serve & sleep 5 && ollama pull qwen3:0.6b && wait"]
