version: '3.8'
services:
  app:
    image: henry768/redux_todo_in_astro:test
    container_name: redux-todo-astro
    ports:
      - "4321:4321"
    volumes:
      - ./public/data:/app/public/data
    env_file:
      - .env
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

networks:
  default:
    driver: bridge
