apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redux-todo-astro-data
  namespace: redux-todo-astro
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
