apiVersion: v1
kind: Service
metadata:
  name: redux-todo-astro
  namespace: redux-todo-astro
  labels:
    app: redux-todo-astro
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: redux-todo-astro
