apiVersion: apps/v1
kind: Deployment
metadata:
  name: redux-todo-astro
  namespace: redux-todo-astro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redux-todo-astro
  template:
    metadata:
      labels:
        app: redux-todo-astro
    spec:
      containers:
      - name: redux-todo-astro
        image: henry768/redux-todo-astro:latest
        imagePullPolicy: IfNotPresent
        command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--watch.usePolling"]
        ports:
        - containerPort: 4321
          name: http
        - containerPort: 24678
          name: websocket
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Increase the initial delay and add more buffer time for the dev server to start
        readinessProbe:
          httpGet:
            path: /
            port: 4321
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /
            port: 4321
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 5
        env:
        - name: NODE_ENV
          value: "development"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "4321"
        - name: ASTRO_TELEMETRY_DISABLED
          value: "1"
        - name: IS_KUBERNETES
          value: "true"
        - name: VITE_HMR_PROTOCOL
          value: "ws"
        - name: VITE_HMR_HOST
          value: "0.0.0.0"
        - name: VITE_HMR_PORT
          value: "24678"
        - name: VITE_HMR_CLIENT_PORT
          value: "24678"
