apiVersion: apps/v1
kind: Deployment
metadata:
  name: redux-todo-astro-prod
  namespace: redux-todo-astro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redux-todo-astro-prod
  template:
    metadata:
      labels:
        app: redux-todo-astro-prod
    spec:
      containers:
      - name: redux-todo-astro
        image: redux-todo-astro:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4321
          name: http
        - containerPort: 24678
          name: websocket
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 4321
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 4321
          initialDelaySeconds: 15
          periodSeconds: 10
        env:
        - name: NODE_ENV
          value: "development"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "4321"
        - name: ASTRO_TELEMETRY_DISABLED
          value: "1"
        - name: VITE_HMR_PROTOCOL
          value: "ws"
        - name: VITE_HMR_HOST
          value: "0.0.0.0"
        - name: VITE_HMR_PORT
          value: "24678"
        - name: VITE_HMR_CLIENT_PORT
          value: "24678"
