name: Build Status Checking Service Docker Image

on:
  push:
    branches: 
      - main
      - develop
    tags:
      - 'status-v*'
  pull_request:
  workflow_dispatch:

env:
  IMAGE_NAME: henry768/status-checking-service
  
jobs:
  build-and-push:
    name: Build and Push Status Checking Service Docker image
    runs-on: ubuntu-latest
    environment: docker
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
      
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: henry768
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./status_checking
          file: ./status_checking/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
