name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:    # Adding manual trigger option

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # This ensures we fetch the full git history

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

  generate-logs:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate 24h Git Log
      run: |
        echo "# Git Activity Log (Last 24 Hours)" > git_log.md
        echo "Generated at: $(date)" >> git_log.md
        echo "## Commits" >> git_log.md
        git log --since="24 hours ago" --pretty=format:"* %h - %s (%cr) by %an" >> git_log.md

    - name: Upload Git Log
      uses: actions/upload-artifact@v3
      with:
        name: git-activity-log
        path: git_log.md