name: Build and Push Docker Image redux_todo_astro

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_HUB_REPOSITORY: henry768/redux-todo-astro

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: henry768
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: henry768/redux-todo-astro:latest, henry768/redux-todo-astro:${{ github.sha }}
          cache-from: type=registry,ref=henry768/redux-todo-astro:buildcache
          cache-to: type=registry,ref=henry768/redux-todo-astro:buildcache,mode=max
          build-args: |
            ROLLUP_SKIP_NODEJS=true
            npm_config_platform=linux
            npm_config_arch=x64
