name: Build and Push Test Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_HUB_REPOSITORY: henry768/redux_todo_in_astro

jobs:
  build-and-push-test:
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: henry768
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker test image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.test
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.DOCKER_HUB_REPOSITORY }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
