name: Get Telegram Chat ID

on:
  workflow_dispatch:

jobs:
  get-chat-id:
    runs-on: ubuntu-latest
    environment: telegram-bot
    
    steps:
    - name: Get Chat ID
      run: |
        curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/getUpdates" | jq '.result[] | .message.chat.id' | sort -u
