name: Get Chat ID

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  get-id:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Updates
      run: |
        curl -s "https://api.telegram.org/bot7791170991:AAGm4-_s2RWctpAHDg-3h2WmE50N19C95ok/getUpdates" | jq .
