name: Git Log

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to look back'
        required: false
        default: '1'
        type: string

jobs:
  generate-log:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Display Git Log
      run: |
        echo "==================== GIT ACTIVITY LOG ===================="
        echo "Generated at: $(date)"
        echo "======================================================"
        echo
        echo "COMMITS FROM LAST ${{ github.event.inputs.days || 1 }} DAY(S):"
        echo "======================================================"
        git log --since="${{ github.event.inputs.days || 1 }} days ago" \
            --pretty=format:'%C(yellow)%h%Creset - %C(cyan)%ad%Creset - %C(bold blue)%an%Creset%n%s%n%b' \
            --date=format:'%Y-%m-%d %H:%M:%S'
        echo
        echo "======================================================"
        echo "Total commits: $(git log --since="${{ github.event.inputs.days || 1 }} days ago" --oneline | wc -l)"
        echo "======================================================"