name: Git Log

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:      # Manual trigger with optional date input
    inputs:
      days:
        description: 'Number of days to look back'
        required: false
        default: '1'
        type: string

permissions:
  issues: write
  contents: read

jobs:
  generate-log:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate Git Log
      run: |
        echo "# Git Activity Log" > git_log.md
        echo "Generated at: $(date)" >> git_log.md
        echo "## Commits" >> git_log.md
        git log --since="${{ github.event.inputs.days || 1 }} days ago" --pretty=format:"* %h - %s (%cr) by %an" >> git_log.md

    - name: Create Git Log Issue
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const log = fs.readFileSync('git_log.md', 'utf8');
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.name,
            title: `Git Activity Log - ${new Date().toISOString().split('T')[0]}`,
            body: log
          });