name: Git Log

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to look back'
        required: false
        default: '1'
        type: string

permissions:
  contents: write

jobs:
  generate-log:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Docs Directory
      run: |
        mkdir -p Docs/log/users
        mkdir -p Docs/log/submodules

    - name: Generate Git Log
      run: |
        # Generate main log file
        echo "# Git Activity Log" > "Docs/log/git-log-$(date +%Y-%m-%d).md"
        echo "Generated at: $(date)" >> "Docs/log/git-log-$(date +%Y-%m-%d).md"
        
        # Get first and last commit hashes
        FIRST_COMMIT=$(git log --since="${{ github.event.inputs.days || 1 }} days ago" --reverse --format="%H" | head -n 1)
        LAST_COMMIT=$(git log --since="${{ github.event.inputs.days || 1 }} days ago" --format="%H" | head -n 1)
        
        # Generate main diff log
        echo "## Changes Between First and Last Commits" >> "Docs/log/git-log-$(date +%Y-%m-%d).md"
        echo "\`\`\`diff" >> "Docs/log/git-log-$(date +%Y-%m-%d).md"
        if [ ! -z "$FIRST_COMMIT" ] && [ ! -z "$LAST_COMMIT" ]; then
          git diff $FIRST_COMMIT..$LAST_COMMIT -- . ':!node_modules' ':!package-lock.json' >> "Docs/log/git-log-$(date +%Y-%m-%d).md"
        else
          echo "No commits found in the specified timeframe" >> "Docs/log/git-log-$(date +%Y-%m-%d).md"
        fi
        echo "\`\`\`" >> "Docs/log/git-log-$(date +%Y-%m-%d).md"
        
        # Generate per-user logs in their respective folders
        for author in $(git log --since="${{ github.event.inputs.days || 1 }} days ago" --format="%ae" | sort -u); do
          username=$(echo "$author" | cut -d@ -f1)
          mkdir -p "Docs/log/users/$username"
          
          echo "# Git Activity Log - $author" > "Docs/log/users/$username/git-log-$(date +%Y-%m-%d).md"
          echo "Generated at: $(date)" >> "Docs/log/users/$username/git-log-$(date +%Y-%m-%d).md"
          echo "## Changes by $author" >> "Docs/log/users/$username/git-log-$(date +%Y-%m-%d).md"
          echo "\`\`\`diff" >> "Docs/log/users/$username/git-log-$(date +%Y-%m-%d).md"
          git log --since="${{ github.event.inputs.days || 1 }} days ago" --author="$author" --patch --no-merges -- . ':!node_modules' ':!package-lock.json' >> "Docs/log/users/$username/git-log-$(date +%Y-%m-%d).md"
          echo "\`\`\`" >> "Docs/log/users/$username/git-log-$(date +%Y-%m-%d).md"
          echo "## Summary" >> "Docs/log/users/$username/git-log-$(date +%Y-%m-%d).md"
          echo "Total commits by $author: $(git log --since="${{ github.event.inputs.days || 1 }} days ago" --author="$author" --oneline | wc -l)" >> "Docs/log/users/$username/git-log-$(date +%Y-%m-%d).md"
        done
        
        # Submodule Log Generation
        echo "# Submodule Git Logs" > "Docs/log/submodules/submodule-log-$(date +%Y-%m-%d).md"
        echo "Generated at: $(date)" >> "Docs/log/submodules/submodule-log-$(date +%Y-%m-%d).md"
        
        # Iterate through submodules
        git submodule foreach '
          echo "## Submodule: $name" >> "../../../Docs/log/submodules/submodule-log-$(date +%Y-%m-%d).md"
          echo "### Recent Commits" >> "../../../Docs/log/submodules/submodule-log-$(date +%Y-%m-%d).md"
          echo "\`\`\`" >> "../../../Docs/log/submodules/submodule-log-$(date +%Y-%m-%d).md"
          git log --since="${{ github.event.inputs.days || 1 }} days ago" --oneline >> "../../../Docs/log/submodules/submodule-log-$(date +%Y-%m-%d).md"
          echo "\`\`\`" >> "../../../Docs/log/submodules/submodule-log-$(date +%Y-%m-%d).md"
          
          echo "### Diff" >> "../../../Docs/log/submodules/submodule-log-$(date +%Y-%m-%d).md"
          echo "\`\`\`diff" >> "../../../Docs/log/submodules/submodule-log-$(date +%Y-%m-%d).md"
          git diff HEAD~$((1)) HEAD >> "../../../Docs/log/submodules/submodule-log-$(date +%Y-%m-%d).md"
          echo "\`\`\`" >> "../../../Docs/log/submodules/submodule-log-$(date +%Y-%m-%d).md"
        '
        
        echo -e "\n## Summary" >> "Docs/log/git-log-$(date +%Y-%m-%d).md"
        echo "Total commits: $(git log --since="${{ github.event.inputs.days || 1 }} days ago" --oneline | wc -l)" >> "Docs/log/git-log-$(date +%Y-%m-%d).md"

    - name: Commit and Push Log
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Docs/log/
        git commit -m "docs: update git log for $(date +%Y-%m-%d)" || echo "No changes to commit"
        git push origin HEAD:main