name: Markdown to PDF Converter for Each User

on:
  workflow_dispatch:
    inputs:
      user_folder:
        description: 'Specific user folder to process (leave empty for all users)'
        required: false
        type: string
permissions:
  contents: write

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest
    environment: LLM_API_KEY

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-pictures
        pip install --upgrade google-generativeai
        pip install python-dotenv

    - name: Find and Convert Latest MD to PDF
      env:
        GOOGLE_API_KEY: "AIzaSyAPz0ODezXu39YHYaaSUAsKMBhjKwlYJFo"
        USER_FOLDER: ${{ github.event.inputs.user_folder }}
      run: |
        cp Docs/config/codeVault/convert_md_to_pdf_each_user.py .
        
        # Find all user folders
        if [ -n "$USER_FOLDER" ]; then
          user_folders="Docs/analysis/users/$USER_FOLDER"
        else
          user_folders=$(find Docs/analysis/users -mindepth 1 -maxdepth 1 -type d)
        fi
        
        # Process each user folder
        for user_dir in $user_folders; do
          # Find the latest formatted-analysis file
          latest_md=$(find "$user_dir" -name "formatted-analysis-*.md" | sort -r | head -n 1)
          if [ -n "$latest_md" ]; then
            echo "Processing: $latest_md"
            python convert_md_to_pdf_each_user.py "$latest_md"
          fi
        done

    - name: Commit PDFs
      run: |
        mkdir -p Docs/analysis/progress_reports
        mv *.pdf Docs/analysis/progress_reports/ 2>/dev/null || true
        
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        git add Docs/analysis/progress_reports/*.pdf
        git commit -m "docs: update progress report PDFs" || echo "No changes to commit"
        git push origin HEAD:main