name: Markdown to PDF Converter

on:
  workflow_dispatch:
    inputs:
      markdown_file:
        description: 'Docs/analysis/[test][report]2025-02-22.md'
        required: true
        type: string
        default: 'README.md'

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest
    environment: LLM_API_KEY

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-pictures
        pip install --upgrade google-generativeai
        pip install python-dotenv

    - name: Convert MD to PDF
      env:
        GOOGLE_API_KEY: "AIzaSyBZ52gRnYBjfyyh4jiEWscKoRfTx-j4YEQ"
      run: |
        cat << 'EOF' > convert_md_to_pdf.py
        import os
        import google.generativeai as genai
        import subprocess

        # Configure Gemini
        api_key = os.getenv('GOOGLE_API_KEY')
        if not api_key:
            raise ValueError("GOOGLE_API_KEY not set")

        genai.configure(api_key=api_key)
        model = genai.GenerativeModel('gemini-2.0-pro-exp-02-05')

        def create_pdf(latex_content, output_name):
            # Write LaTeX content to file
            tex_path = f"{output_name}.tex"
            with open(tex_path, "w", encoding='utf-8') as f:
                f.write("""\\documentclass{article}
                \\usepackage[utf8]{inputenc}
                \\usepackage{xcolor}
                \\usepackage{tikz}
                \\usepackage{listings}
                \\usepackage{graphicx}

                \\begin{document}
                """ + latex_content + """
                \\end{document}
                """)
            print(f"LaTeX file saved at: {os.path.abspath(tex_path)}")

            # Run pdflatex in the current directory
            for _ in range(2):
                result = subprocess.run(
                    ['pdflatex', '-interaction=nonstopmode', tex_path],
                    capture_output=True,
                    text=True,
                    cwd=os.path.dirname(os.path.abspath(tex_path)) or '.'
                )
                print("LaTeX Output:", result.stdout)
                if result.returncode != 0:
                    print("LaTeX Error:", result.stderr)
                    if os.path.exists(f"{output_name}.log"):
                        with open(f"{output_name}.log", 'r') as log:
                            print("LaTeX Log:", log.read())
                    raise Exception("PDF generation failed")

            pdf_path = f"{output_name}.pdf"
            if os.path.exists(pdf_path):
                print(f"PDF generated successfully at: {os.path.abspath(pdf_path)}")
            else:
                raise Exception(f"PDF file not created at: {os.path.abspath(pdf_path)}")

        def md_to_latex(md_content):
            prompt = """
              You are a LaTeX document formatter. Convert the following structured Markdown content into a properly formatted LaTeX document. Ensure the following:

              - Do not use ```latex ``` or any similar code block delimiters.
              - Use the appropriate document class, title, and sections.
              - [!IMPORTANT] Correctly format bold text, italic text, etc. (** --> \\textbf, * --> \\textit)
              - Correctly format tables, numbering, bullet points, and code blocks.
              - Maintain the full content without reduction.
              - Convert mermaid graphs into TikZ pictures using the specified styles in vertical style ("below of"):

              % Custom styles for all diagrams
                  \\tikzset{
                      block/.style={
                          rectangle,
                          draw=darkblue,
                          text width=7em,
                          text centered,
                          rounded corners,
                          minimum height=2em,
                          fill=lightgray!10,
                          font=\\small
                      },
                      process/.style={
                          rectangle,
                          draw=forestgreen,
                          text width=6em,
                          text centered,
                          rounded corners,
                          fill=lightgray!30,
                          minimum height=2em,
                          font=\\small
                      },
                      line/.style={
                          draw,
                          -latex',
                          font=\\footnotesize
                      },
                      cloud/.style={
                          draw,
                          ellipse,
                          minimum width=2cm,
                          minimum height=1cm,
                          fill=lightgray!20
                      },
                      state/.style={
                          rectangle,
                          draw=uiblue,
                          text width=8em,
                          text centered,
                          rounded corners,
                          fill=uiblue!10,
                          minimum height=2.5em,
                          font=\\small
                      }
                  }
                  - note the color rgb format:
                      - lightgray, RGB(240,240,240)
                      - darkblue, RGB(0,0,139)
                      - forestgreen, RGB(34,139,34)
                      - uiblue, RGB(66,139,202)

              Markdown Content:
              """ + md_content

            response = model.generate_content(prompt)
            return response.text

        def create_pdf(latex_content, output_name):
            # Write LaTeX content to file
            tex_path = f"{output_name}.tex"
            with open(tex_path, "w", encoding='utf-8') as f:
                f.write("""\\documentclass{article}
                \\usepackage[utf8]{inputenc}
                \\usepackage{xcolor}
                \\usepackage{tikz}
                \\usepackage{listings}
                \\usepackage{graphicx}

                \\begin{document}
                """ + latex_content + """
                \\end{document}
                """)
            print(f"LaTeX file saved: {tex_path}")

            # Get the directory of the tex file
            tex_dir = os.path.dirname(tex_path)
            
            # Run pdflatex with error handling
            for _ in range(2):
                result = subprocess.run(
                    ['pdflatex', '-interaction=nonstopmode', '-output-directory', tex_dir, tex_path],
                    capture_output=True,
                    text=True
                )
                if result.returncode != 0:
                    print("LaTeX Error:", result.stderr)
                    with open(f"{output_name}.log", 'r') as log:
                        print("LaTeX Log:", log.read())
                    raise Exception("PDF generation failed")
            
            pdf_path = f"{output_name}.pdf"
            if os.path.exists(pdf_path):
                print(f"PDF generated successfully: {pdf_path}")
            else:
                raise Exception("PDF file was not created")

        # Read input markdown file from Docs/analysis
        md_file = "${{ github.event.inputs.markdown_file }}"
        output_name = os.path.splitext(md_file)[0]
        
        # Ensure the output directory exists
        os.makedirs(os.path.dirname(md_file), exist_ok=True)

        with open(md_file, 'r', encoding='utf-8') as f:
            md_content = f.read()

        # Convert to LaTeX and create PDF
        latex_content = md_to_latex(md_content)
        create_pdf(latex_content, output_name)

        # Clean up auxiliary files
        for ext in [".aux", ".log", ".out"]:
            aux_file = output_name + ext
            if os.path.exists(aux_file):
                os.remove(aux_file)
        EOF

        # Run the conversion script with debug info
        echo "Current directory: $(pwd)"
        echo "Directory contents before conversion:"
        ls -la
        python convert_md_to_pdf.py
        echo "Directory contents after conversion:"
        ls -la

    - name: Debug LaTeX Output
      if: always()
      run: |
        echo "Generated files:"
        ls -la *.tex *.pdf *.log || true

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4  # Updated from v3 to v4
      with:
        name: converted-pdf
        path: "*.pdf"

    - name: Debug file location
      run: |
        pwd
        ls -la
        echo "Looking for PDF in current directory"

    - name: Commit PDF
      run: |
        pdf_file="${{ github.event.inputs.markdown_file }}"
        pdf_file="${pdf_file%.md}.pdf"
        echo "Looking for PDF file: $pdf_file"
        
        if [ -f "$pdf_file" ]; then
          echo "PDF file found"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add "$pdf_file"
          git commit -m "docs: convert markdown to PDF"
          git push origin HEAD:main
        else
          echo "PDF file not found at: $pdf_file"
          echo "Current directory contents:"
          ls -la
          exit 1
        fi

        git add "*.pdf"
        git commit -m "docs: convert markdown to PDF" || echo "No changes to commit"
        git push origin HEAD:main