name: Playwright CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Start dev server (localhost:4321)
      run: npm run dev &
      env:
        NODE_ENV: development

    - name: Start Python REPL server
      run: node server/python-server.js &
      env:
        NODE_ENV: development

    - name: Wait for servers to be ready
      run: |
        echo "Waiting for servers to start..."
        sleep 10

    - name: Run Playwright script
      run: node src/pages/api/Playwright_Python_REPL.js

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      with:
        name: playwright-screenshots
        path: |
          step1.png
          step2.png
          step3.png
          step4.png
          step5.png
          step6.png
          step7.png
