name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libglib2.0-0 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libdbus-1-3 \
          libxkbcommon0 \
          libx11-6 \
          libxcomposite1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxrandr2 \
          libgbm1 \
          libpango-1.0-0 \
          libcairo2 \
          libasound2t64 || true
    
    - name: Install dependencies
      run: |
        # Use install instead of ci to update lock file with current package.json
        npm install --no-fund --no-audit
        npm install -D @playwright/test
        npx playwright install --with-deps chromium
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    
    - name: Print diagnostic information
      run: |
        echo "Node version: $(node --version)"
        echo "npm version: $(npm --version)"
        echo "Current directory: $(pwd)"
        echo "Listing files:"
        ls -la
    
    - name: Start dev server in background
      run: |
        npm run start & 
        sleep 15
        echo "Dev server started in background"
    
    - name: Run Playwright tests
      run: |
        echo "Running Playwright tests..."
        npx playwright test
      env:
        CI: true
        DEBUG: pw:api
    
    - name: Upload server logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: server-logs
        path: |
          *.log
          logs/
        retention-days: 5
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 5
    
    - name: Upload test screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-screenshots
        path: tests/data/
        retention-days: 5
