name: Playwright CLM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Remove cards.db file
      run: |
        echo "Deleting public/data/cards.db if exists..."
        rm -f public/data/cards.db

    - name: Start dev server (localhost:4321)
      run: npm run dev &
      env:
        NODE_ENV: development

    - name: Start Python REPL server
      run: node server/python-server.js &
      env:
        NODE_ENV: development

    - name: Wait for servers to be ready
      run: |
        echo "Waiting for servers to start..."
        sleep 10

    - name: Run Playwright script
      run: node src/pages/api/Playwright_CLM_Conversational_Programming.js

    - name: Upload screenshots as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: playwright-screenshots
        path: |
          step1.png
          step2.png
          step3.png
          step4.png
          step5.png
          step6.png
          step7.png
          step8.png
          step9.png
          step10.png
          step11.png
          step12.png
          step13.png
          step14.png

    - name: Commit playwright_logs to repo
      if: success()
      run: |
        mkdir -p playwright_logs/playwrightclmconversationalprogramming
        cp step*.png playwright_logs/playwrightclmconversationalprogramming/ || echo "No logs found"

        echo "Process logs" > playwright_logs/playwrightclmconversationalprogramming/log.txt
        echo "Checkout repository" >> playwright_logs/playwrightclmconversationalprogramming/log.txt
        echo "Setup Node.js" >> playwright_logs/playwrightclmconversationalprogramming/log.txt
        echo "Install dependencies" >> playwright_logs/playwrightclmconversationalprogramming/log.txt
        echo "Install Playwright browsers" >> playwright_logs/playwrightclmconversationalprogramming/log.txt
        echo "Remove cards.db file" >> playwright_logs/playwrightclmconversationalprogramming/log.txt
        echo "Start dev server" >> playwright_logs/playwrightclmconversationalprogramming/log.txt
        echo "Start Python REPL server" >> playwright_logs/playwrightclmconversationalprogramming/log.txt
        echo "Wait for servers" >> playwright_logs/playwrightclmconversationalprogramming/log.txt
        echo "Run Playwright script" >> playwright_logs/playwrightclmconversationalprogramming/log.txt
        echo "Upload screenshots as artifacts" >> playwright_logs/playwrightclmconversationalprogramming/log.txt
        echo "Commit playwright_logs to repo" >> playwright_logs/playwrightclmconversationalprogramming/log.txt

        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        git pull origin main
        git add playwright_logs/
        git commit -m "chore(ci): add latest playwright_logs [CI]" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
