name: Audio Transcription

on:
  push:
    paths:
      - 'Docs/analysis/raw/audio/**'
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  transcribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for pushing transcripts
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt
          
      - name: Run transcription
        run: python Docs/analysis/audio_transcriber.py
        
      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet Docs/analysis/processed/transcript/ || echo "changes=true" >> $GITHUB_OUTPUT
        
      - name: Commit and push transcripts
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Docs/analysis/processed/transcript/
          git commit -m "Add transcripts for new audio files [skip ci]"
          git push
